Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  (1..3).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.hostname = "hadoop-worker#{i}"
      worker.vm.network "private_network", ip: "192.168.56.#{i+1}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = "4"
      end
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
     systemctl restart sshd.service
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end
end