---
- hosts: all
  tasks: 
    - name: Install java 11
      become: true
      apt:   
        name: openjdk-11-jdk 
        state: present
    - name: Intall openssh server
      become: true
      apt: 
        name: openssh-server
        state: present
    - name: Intall openssh client
      become: true
      apt: 
        name: openssh-client
    - name: Start openssh-server
      become: true
      service: 
        name: sshd
        state: started
    
    - name: Install wget
      become: true
      apt:   
        name: wget
        state: present

    - name: Download hadoop
      shell: wget http://apache.rediris.es/hadoop/core/hadoop-3.3.1/hadoop-3.3.1.tar.gz
    - name: Unzip haddop
      shell: tar -xzf hadoop-3.3.1.tar.gz
    - name: Move hadoop to opt
      become: true
      shell: mv hadoop-3.3.1 /opt/hadoop

    - name: Copy configured hadoop-env
      copy:
        src: hadoop 
        dest: /opt/hadoop/etc/

    - name: Create enviroment variables
      shell: |
        echo HADOOP_HOME=/opt/hadoop >> .bashrc
        echo JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ >> .bashrc
        echo PATH=$PATH:$HADOOP_HOME/bin:$JAVA_HOME/bin >> .bashrc

    - name: Map host names
      become: true
      shell: |
        echo 192.168.56.1    hadoop-master >> /etc/hosts
        echo 192.168.56.2    hadoop-worker1 >> /etc/hosts
        echo 192.168.56.3    hadoop-worker2 >> /etc/hosts

