Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    worker1.vm.network "private_network", ip: "192.168.56.2"
    worker1.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = "2"
    end
  end
  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network", ip: "192.168.56.3"
    worker2.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = "2"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
     systemctl restart sshd.service
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end

  #config.vm.provision "shell", inline: <<-SHELL
  #   echo HADOOP_HOME=/opt/hadoop >> .bashrc
  #   echo JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ >> .bashrc
  #   echo PATH=$PATH:$HADOOP_HOME/bin:$JAVA_HOME/bin >> .bashrc
  #SHELL
end